name: kiara-streamlit
channels:
  - conda-forge
  - dharpa
dependencies:
  - python ==3.10
  - kiara_plugin.network_analysis
  - kiara_plugin.language_processing
  - pip:
    - git+https://github.com/hostuser/kiara_plugin.streamlit@develop
